# broadcasting

In [4]:
import numpy as np

x = np.array([12,34,34,2,43,76,82])
y = x+210
print(y)

mean = x.mean(axis=0)
print(mean)
z = x-mean
print(z)

[222 244 244 212 253 286 292]
40.42857142857143
[-28.42857143  -6.42857143  -6.42857143 -38.42857143   2.57142857
  35.57142857  41.57142857]


# dot product

In [14]:
a = np.array([1,2,3,4,5])
b = np.array([[2,23,43,54,87],
            [23,5,54,67,45],
            [23,54,87,2,82]])
print(b@a)

c = np.array([[12,34,56],
            [23,5,54],
            [23,54,87],
            [23,54,87],
            [90,82,55]
            ])
print(b@c)

[828 688 810]
[[10614 12555 14578]
 [ 7224 11031 14560]
 [10945 12582 16457]]
